Address suggestions from Samuel's final proofreading
cfrg/draft-irtf-cfrg-aegis-aead pull request #84
Opened 2024-12-31 00:10 UTC by jedisct1

Apply pretty much all the suggestions from #73 #74 #75 #76 #77 #78 #79 #81 #82 and #83

Since the RGLC is technically over, we're not supposed to make significant changes. Grammar fixes and stylistic adjustments are fine, but deeper changes might indicate that the draft requires more time and a new RGLC. For this reason, the few instances where an alternative was proposed but you explicitly stated that you were also fine with the status quo have not been included here.

A few other changes were not included because they require further discussion.

2025-01-01 11:42 UTC, samuel-lucas6 requested changes
Thanks for doing this; you beat me to it. Left some comments for a few edits/questions. I've skipped some of my feedback where I agree that it's fine as is.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
Do you think splitting up this section is too big of a change after the RGLC?

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
Do you think `mod` is clearer than `%`?

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ZeroPad(x, n)`: padding operation. Trailing zeros are concatenated to `x` until the total length is a multiple of `n` bits.
What I meant with these is for some functions we have `padding operation.`/`truncation operations.`, etc, whereas others just start with `returns ...`. I think this should be consistent, and the operation is implied from the function name.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ZeroPad(x, n)`: padding operation. Trailing zeros are concatenated to `x` until the total length is a multiple of `n` bits.
Also, I'm not it's clear that no padding should happen if `x` is empty (e.g., an empty `ad` or `msg` doesn't get padded/absorbed into the state). This is quite important.

This change would require modifications to the Stream Cipher pseudocode though.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `CtEq(a, b)`: compares `a` and `b` in constant-time, returning `True` for an exact match, and `False` otherwise.
The comma before `and` can be removed.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `AESRound(in, rk)`: a single round of the AES encryption round function, which is the composition of the `SubBytes`, `ShiftRows`, `MixColums`, and `AddRoundKey` transformations, as defined in secti
`section 5` can be capitalised. The NIST document does this when referring to a number.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Distinct associated data inputs, as described in {{!RFC5116, Section 3}} MUST be unambiguously encoded as a single input.
Could add a comma after `Section 3}}` or rephrase to `single input, as described in {{!RFC5116, Section 3}}`.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
Do you think it's unnecessary to list the tag/key/nonce lengths here with a MUST?

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
Also, I think adding `erase expected_tag` after `erase msg` in the Authenticated Decryption pseudocode sections makes sense given this is what we say in the text.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Distinct associated data inputs, as described in {{!RFC5116, Section 3}} MUST be unambiguously encoded as a single input.
Could add a comma after `Section 3}}` or rephrase to `single input, as described...`.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
See higher up comment about the tag/key/nonce lengths.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Distinct associated data inputs, as described in {{!RFC5116, Section 3}} MUST be unambiguously encoded as a single input.
These bits could be moved to the Authenticated Encryption `Security:` section.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `xi`: the 128-bit input block.
This matches AEGIS-128L, but there are other instances of the same thing below that don't at the moment.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  Update(M0, M1)
Could add in `erase expected_tag` after `erase msg` in Authenticated Decryption, as discussed for AEGIS-128L/-256.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  After initialization, the `Update` function is called with constant parameters, allowing further optimizations.
What about `allowing values to be cached` or similar?

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  All AEGIS variants can be used to construct a MAC.
I would think defining MAC in brackets is required by the style guides, although I haven't checked this, and it would be annoying given the section title. We could leave it and see what the editor/whoever does.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +else:              # 256 bits
Think these comments need to be shifted right to match the top one.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +else:              # 256 bits
Think these comments need to be shifted right to match the top one.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>      tag = V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0] ^ V[4,0] ^ V[5,0] ^ V[6,0]
Doesn't this correspond to AEGIS-128X, not AEGIS-256X? AEGIS-256X doesn't have this many states.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>      tag = t0 || t1
Missing `return tag`.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
Space to remove at `~ 2<sup>-33</sup>`. We don't have a space after `~` elsewhere.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> The selected hash function must ensure a minimum of 128-bit preimage resistance.

Is this definitely correct? I've brought this up several times because surely there's an attack based on collision resistance (a collision = the same associated data)? The commitment papers always discuss collision resistance.

I think this should be changed to say `128-bit collision resistance`.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
I think `appending their lengths` => `their little-endian encoded lengths` is useful as an example.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  AEGIS nonces match the size of the key. AEGIS-128L and AEGIS-128X feature 128-bit nonces, offering an extra 32 bits compared to the commonly used AEADs in IETF protocols. The AEGIS-256 and AEGIS-256X
`current IETF protocols` or `at the time of writing` as this may change.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +The security of AEGIS against timing and physical attacks is limited by the implementation of the underlying `AESRound` function. Failure to implement `AESRound` in a fashion safe against timing and
I think `also` from `also depend on` can be removed here.

2025-01-01 11:42 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- Bart Mennink and Charlotte Lefevre, as well as Takanori Isobe and Mostafizar Rahman for investigating the committing security of the schemes specified in this document.
Add a comma after `Rahman`, or we could list them like:

`Bart Mennink, Charlotte Lefevre, Takanori Isobe, and Mostafizar Rahman for`

2025-01-05 17:14 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
I think this is already way too many changes.

2025-01-05 17:15 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
`mod` has both a mathematical meaning, and a meaning for implementers. `%` does not, and reduces clarity, IMHO.

2025-01-05 17:29 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ZeroPad(x, n)`: padding operation. Trailing zeros are concatenated to `x` until the total length is a multiple of `n` bits.
The fact that zeros are concatenated is important. "padding" doesn't tell if the zeros are added before or after the data. How about adding `If x is already a multiple of n bits (including the case when x is zero), no padding is added.`?

For the Stream Cipher pseudocode, we can change the code to:

```text
   if len = 0:
       return {} 
   else:
       stream, tag = Encrypt(ZeroPad({ 0 }, len), {}, key, nonce)
       return stream
```

2025-01-05 17:36 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
My reasoning with preimage resistance was that it makes it impossible to set the AES words of the state to specific values. A hash function with a large output but no preimage resistance would be useless to prevent the attack.

But obviously, if the hash function is not collision resistant, different ADs would produce the same state.

So, we need both.

2025-01-05 21:28 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `ZeroPad(x, n)`: padding operation. Trailing zeros are concatenated to `x` until the total length is a multiple of `n` bits.
Done. Let me know what you think!

2025-01-05 21:28 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `CtEq(a, b)`: compares `a` and `b` in constant-time, returning `True` for an exact match, and `False` otherwise.
Done.

2025-01-05 21:28 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `AESRound(in, rk)`: a single round of the AES encryption round function, which is the composition of the `SubBytes`, `ShiftRows`, `MixColums`, and `AddRoundKey` transformations, as defined in secti
Done.

2025-01-05 21:29 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
Collision resistance added.

2025-01-05 21:34 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
Mentioning a very specific encoding feels a bit off, as this is not a specification, just a generic recommendation. A separated text representation of the length, or usage of a serialization format such as Protobuf would be perfectly fine as well. The best representation is application-dependent.
Even in the absence of SHOULD or MUST, mentioning a byte ordering really feels like it's part of a specification, and that it will allow interoperability. But it doesn't.
I think we should just mention the idea of including a length, so that users think about this, and the implications of not having proper separation. And then they can decide the best way to handle the problem for their use case.

2025-01-05 21:35 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  AEGIS nonces match the size of the key. AEGIS-128L and AEGIS-128X feature 128-bit nonces, offering an extra 32 bits compared to the commonly used AEADs in IETF protocols. The AEGIS-256 and AEGIS-256X
Maybe not "current", as IETF protocols using primitives with a larger nonce may already exist.

"at the time or writing" has been added, then.

2025-01-05 21:36 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- Bart Mennink and Charlotte Lefevre, as well as Takanori Isobe and Mostafizar Rahman for investigating the committing security of the schemes specified in this document.
{ Bart, Charlotte } and { Takanori, Mostafizar } worked independently, so I wouldn't put them all in the same list.

A comma has been added after `Rahman`.

2025-01-05 21:36 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +The security of AEGIS against timing and physical attacks is limited by the implementation of the underlying `AESRound` function. Failure to implement `AESRound` in a fashion safe against timing and
`also` removed, thanks!

2025-01-05 22:21 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +Distinct associated data inputs, as described in {{!RFC5116, Section 3}} MUST be unambiguously encoded as a single input.
Added a comma.

2025-01-05 22:22 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +Distinct associated data inputs, as described in {{!RFC5116, Section 3}} MUST be unambiguously encoded as a single input.
Added a comma. We shouldn't move things unless really necessary.

2025-01-05 22:23 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  Update(M0, M1)
Done.

2025-01-05 22:27 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  All AEGIS variants can be used to construct a MAC.
We didn't define what an AEAD is either, but given the intended audience, this is probably fine.

2025-01-05 22:30 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +else:              # 256 bits
The top one has been moved to the left.

2025-01-05 22:31 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>      tag = V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0] ^ V[4,0] ^ V[5,0] ^ V[6,0]
Oops, good catch, thanks!

2025-01-05 22:32 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>      tag = t0 || t1
Thanks!

2025-01-05 22:32 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
Done.

2025-01-05 22:42 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
The algorithms are impossible to implement with a different tag/key/nonce length.

Whereas the explicit mention of the limits for `ct`, `msg` and `ad` suggests that implementers should check for this at runtime, or use appropriate types.

2025-01-05 22:47 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  After initialization, the `Update` function is called with constant parameters, allowing further optimizations.
See my answer in the issues. Many different types of optimizations can happen. Optimizing compilers are likely to completely remove the XORs rather than caching zeros. Users can also manually write a specialized `Enc` function if that can help (or in assembly). I think it's better to just hint at the fact that it enables optimizations.

2025-01-05 22:49 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
> Do you think it's unnecessary to list the tag/key/nonce lengths here with a MUST?

No, because it's impossible to implement with different sizes.

> Also, I think adding erase expected_tag after erase msg in the Authenticated Decryption pseudocode sections makes sense given this is what we say in the text.

Done.

2025-01-06 20:59 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
I'm sorry for not doing this earlier; I kept not getting around to it. There are quite a few changes, but this seems relatively minor to me as it's basically rearranging. However, it's ok as is so don't mind here. It was more being consistent with the papers.

2025-01-06 21:01 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `a mod b`: the remainder of the Euclidean division between `a` as the dividend and `b` as the divisor.
That makes sense. This suggestion was motivated by the splitting operations and functions up suggestion above.

2025-01-06 21:05 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  - `key`: the encryption key.
> No, because it's impossible to implement with different sizes.

I agree nobody should be implementing it with different sizes. It was a precautionary thing really to say MUST. I was thinking maybe someone would use a smaller value and pad it with zeros to the larger size or something, but I guess that wouldn't be stopped by this change anyway.

2025-01-06 21:08 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>  All AEGIS variants can be used to construct a MAC.
I commented about this in the relevant issue. We do actually define AEAD in the Introduction. I don't remember any other abbreviations. I wonder if it would be better defining MAC in the heading, but that might make it too long.

2025-01-06 21:15 UTC, samuel-lucas6 commented
Thanks for reading through everything. I'll take a look tomorrow so I'm fresh, which might also give you time to reply to my new comments.

2025-01-06 21:20 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  All AEGIS variants can be used to construct a MAC.
Given the audience, I still don't think this is useful. The only important thing to highlight is that it is not a keyed hash function, but we already mention this.

2025-01-06 21:23 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +else:              # 256 bits
The diff looks misleading; everything seems to be aligned:

```md
if tag_len_bits == 128:
    for i in 1..D: # tag from state 0 is skipped
        ti = V[0,i] ^ V[1,i] ^ V[2,i] ^ V[3,i] ^ V[4,i] ^ V[5,i]
        tags = tags || ti

else:              # 256 bits
    for i in 1..D: # tag from state 0 is skipped
```

2025-01-06 21:52 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>  All AEGIS variants can be used to construct a MAC.
`MAC` was replaced with `Message Authentication Code (MAC)`.

I originally thought you actually wanted to define what that class of function is.

2025-01-07 17:46 UTC, samuel-lucas6 requested changes
Good work. Just a few finishing touches.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
>      seriesinfo:
`date: 2021` can also be updated to 2022.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +    stream, tag = Encrypt(ZeroPad({ 0 }, len), {}, key, nonce)
Should we specify `0` in hex?

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +if len = 0:
Can change to `==`.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +Protocols mandating a fully committing scheme without that restriction can provide the associated data as input to a cryptographic hash function and use the output as the `ad` parameter of the `Encry
How come only AEGIS-128L and AEGIS-128X? Do you mean because of their 128-bit security level?

I think we can say 128-bit for all of them since newer algorithms have started targeting that rather than 256-bit anyway and that's what the commitment literature recommends.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: `x` is split into `n`-bit blocks, ignoring partial blocks.
I think this is better. However, we could still start each of these functions with `returns`. For example:

> LE64(x): returns the little-endian encoding of unsigned 64-bit integer x.
> ZeroPad(x, n): returns x appended with trailing zeros until its length is a multiple of n bits. No padding is added if x is already a multiple of n bits, including when x is empty.
> Split(x, n): returns x split into n-bit blocks, ignoring partial blocks.

But AESRound(), Repeat(), and CtEq() are fine as is.

What do you think? Or we could get rid of `returns` in all cases.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: `x` is split into `n`-bit blocks, ignoring partial blocks.
`trailing zeros` could probably be changed to just `zeros` due to the word `appended` now as well.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: `x` is split into `n`-bit blocks, ignoring partial blocks.
Oh your next commit addresses this a bit.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +All AEGIS variants can be used to construct a Message Authentication Code (MAC).
I'm happy for this to be capitalised because that's done in some other RFCs, like the BLAKE2/AEAD interface ones. However, we currently have this lowercase in the Introduction:

> authenticated encryption with associated data (AEAD)

Therefore, I think this should either be made lowercase or the AEAD words should be capitalised like in [RFC 5116](https://www.rfc-editor.org/rfc/rfc5116#section-1.1). Up to you.

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `ci`: the 128-bit encrypted input block.
`input` can be removed to match the [AEGIS-128L section](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-aegis-aead-14#section-3.6).

2025-01-07 17:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `ci`: the 128-bit encrypted input block.
In `The Update Function` for [AEGIS-256](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-aegis-aead-14#section-4.4), the following could also be changed to match the [corresponding AEGIS-128L section](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-aegis-aead-14#section-3.4):

`msg: the block to be absorbed.` => `msg: the 128-bit block to be absorbed.`

2025-01-07 17:49 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
>      seriesinfo:
done

2025-01-07 17:49 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +if len = 0:
done.

2025-01-07 17:51 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +Protocols mandating a fully committing scheme without that restriction can provide the associated data as input to a cryptographic hash function and use the output as the `ad` parameter of the `Encry
I originally tried to address your comment in a different way, changed it back, and ended up with that nonsense making more harm than good :)

Reverted.

2025-01-07 17:53 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +All AEGIS variants can be used to construct a Message Authentication Code (MAC).
Authenticated Encryption with Associated Data has been capitalized.

2025-01-07 17:54 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `ci`: the 128-bit encrypted input block.
Good catch. We should be consistent. Changed, thanks!

2025-01-07 17:56 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +    stream, tag = Encrypt(ZeroPad({ 0 }, len), {}, key, nonce)
`0` is a bit, not a byte, so I think we shouldn't use a hex representation here.

2025-01-07 17:58 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: `x` is split into `n`-bit blocks, ignoring partial blocks.
Yes, it now only says `appends`.

2025-01-07 18:39 UTC, jedisct1 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: `x` is split into `n`-bit blocks, ignoring partial blocks.
changed to start with `returns`.

2025-01-07 18:46 UTC, samuel-lucas6 commented on draft-irtf-cfrg-aegis-aead.md
> +- `Split(x, n)`: returns` x` split into `n`-bit blocks, ignoring partial blocks.
Typo with `.

2025-01-07 18:49 UTC, samuel-lucas6 approved these changes
I believe that's everything. Job well done.

2025-01-07 21:29 UTC, merged